apiVersion: v1
kind: Service
metadata:
  name: combined-loadbalancer
spec:
  type: LoadBalancer
  selector:
    web: app
  ports:
    - name: travel-booking
      port: 4000
      targetPort: 4000
      protocol: TCP
    - name: sujith-travel
      port: 3000
      targetPort: 3000
      protocol: TCP
