apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-booking

spec:
  replicas: 3
  selector:
    matchLabels:
      web: app
  template:
    metadata: 
      labels:
        web: app
    spec:
      containers:
        - name: backend
          image: manikanta1432/travel-booking-image:v1.1.0
          ports:
            - containerPort: 4000
          env:
            - name: FRONTEND_URL
              value: "http://localhost:4000"
            - name: MONGODB_URI
              value: "mongodb://travel-ease-mongo:27017/travelEas"

---
apiVersion: v1
kind: Service
metadata:
  name: travel-booking-service
spec:
  selector:
    web: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
  nodePort: 30001

