apiVersion: apps/v1
kind: Deployment
metadata:
  name: sujith-travel-app
spec:
  replicas: 3
  selector:
    matchLabels:
      web: app
  template:
    metadata:
      labels:
        web: app
    spec:
      containers:
        - name: backend
          image: manikanta1432/sujith-project-image:v1.1.0
          ports:
            - containerPort: 3000
          env:
            - name: FRONTEND_URL
              value: "http://app2-frontend:80"
            - name: MONGODB_URI
              value: "mongodb://mongo:27017/eventdb"
---
apiVersion: v1
kind: Service
metadata: 
  name: sujith-travel-service 
spec:
  selector:
    web: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  nodePort: 30002
